name: First Workflow
on:
  push:
    branches:
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: print everything is ok
        run: echo " welcome in world of github actions" 
