name: test-docker
on:
    push:
        branches:
            - main
        paths:
            - "run.sh"
            - "docker-compose.yml"
            - ".github/workflows/push-pr.yml"
            - "Dockerfile"
    pull_request:
        branches:
            - main
        paths:
            - "run.sh"
            - "docker-compose.yml"
            - ".github/workflows/push-pr.yml"
            - "Dockerfile"
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4.2.2
            - name: run tests
              run: docker-compose up
